build(deps): flake8: AttributeError 'EntryPoints' object has no attribute 'get'
https://github.com/python/importlib_metadata/issues/406

This reverts commit a37f30222f4665e539cc6715d0aec70474209518.

Traceback (most recent call last):
  File "~/cihai/cihai-cli/.venv/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "~/cihai/cihai-cli/.venv/lib/python3.7/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "~/cihai/cihai-cli/.venv/lib/python3.7/site-packages/flake8/main/application.py", line 363, in run
    self._run(argv)
  File "~/cihai/cihai-cli/.venv/lib/python3.7/site-packages/flake8/main/application.py", line 350, in _run
    self.initialize(argv)
  File "~/cihai/cihai-cli/.venv/lib/python3.7/site-packages/flake8/main/application.py", line 330, in initialize
    self.find_plugins(config_finder)
  File "~/cihai/cihai-cli/.venv/lib/python3.7/site-packages/flake8/main/application.py", line 153, in find_plugins
    self.check_plugins = plugin_manager.Checkers(local_plugins.extension)
  File "~/cihai/cihai-cli/.venv/lib/python3.7/site-packages/flake8/plugins/manager.py", line 357, in __init__
    self.namespace, local_plugins=local_plugins
  File "~/cihai/cihai-cli/.venv/lib/python3.7/site-packages/flake8/plugins/manager.py", line 238, in __init__
    self._load_entrypoint_plugins()
  File "~/cihai/cihai-cli/.venv/lib/python3.7/site-packages/flake8/plugins/manager.py", line 254, in _load_entrypoint_plugins
    eps = importlib_metadata.entry_points().get(self.namespace, ())
AttributeError: 'EntryPoints' object has no attribute 'get'